# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBRanking_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(db_index=True)),
                ('client_num', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tb_ranking_list',
            },
        ),
    ]
